USE [master]
GO

/****** Object:  Database [CampaignManagement]    Script Date: 2/25/2021 5:47:30 PM ******/
CREATE DATABASE [CampaignManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CampaignManagement', FILENAME = N'D:\ZDAASProjects\DB\CampaignManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CampaignManagement_log', FILENAME = N'D:\ZDAASProjects\DB\CampaignManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CampaignManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CampaignManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CampaignManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CampaignManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CampaignManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CampaignManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [CampaignManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CampaignManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CampaignManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CampaignManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CampaignManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CampaignManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CampaignManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CampaignManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CampaignManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CampaignManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CampaignManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CampaignManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CampaignManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CampaignManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CampaignManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CampaignManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CampaignManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CampaignManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [CampaignManagement] SET  MULTI_USER 
GO

ALTER DATABASE [CampaignManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CampaignManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CampaignManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CampaignManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CampaignManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CampaignManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CampaignManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CampaignManagement] SET  READ_WRITE 
GO


